server:
  port: 8888

spring:
  application:
    name: configuration-management
  cloud:
    config:
      server:
        git:
          uri: https://github.com/example/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/