server:
  port: 9092

spring:
  kafka:
    bootstrap-servers: localhost:9090
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
