server:
  port: 8083

spring:
  application:
    name: service-a

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.cloud.netflix.eureka: DEBUG
